### PR TITLE
Allow PHP 7.0

### PR DESCRIPTION
**Pull request by thePanz**
Allow using the library on PHP 7.0, too

### CODE REVIEW

**Comment by wolfy-j** [comment]
I was trying to avoid that, but I'm fine doing it since we can always revert nullable return types later.

Please, use @inheritdoc for `send` method as well as you did for `receiveSync` so the code is consistent.

**Comment by thePanz** [comment]
@wolfy-j I updated the code and applied some doc-block cleanups :)

**Comment by wolfy-j** [comment]
I've added 7.0 to travis as well.

**Comment by thePanz** [comment]
Thanks! :)

**Pull request merged**
